### ISSUE TITLE
Non symmetic layer doesn't work

### ISSUE THREAD

**Issue by blackhat81** [markmal/freeship-plus-in-lazarus#103]
Hello, i can't perform non symmetric layer feature: i need to deaw a model of a gondola like boats. I've tried precompiled version but i'm not able to perform this option.

**Comment by pafurijaz** [comment]
Hi sadly this app seem abandoned ,only a changes at the beginning of 2023, but basically nothing significant, I don't think there will be any other updates, it's been down for years now  since 2020.

This application should be rewritten in another more modern language, perhaps others could contribute.

**Comment by blackhat81** [comment]
OK. Found a way to perform non symmetric layer feature. 
It seems work fine.

**Comment by markmal** [comment]
@blackhat81 
sounds great!

@pafurijaz 
, yes, I really do not have much time. Busy with work and other stuff.
