### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by koendv** [markmal/freeship-plus-in-lazarus#16]
There is a Lazarus plugin which converts a Lazarus project to a Debian source package: http://prof7bit.github.io/LazPackager/ .

Is it possible to make a Debian source package for Freeship plus? 

Thanks.

**Comment by speters** [comment]
I did first work regarding a Debian package in my "debian" branch (https://github.com/speters/freeship-plus-in-lazarus/tree/debian/debian), which is some commits behind master, because of lack of time (sorry).
Maybe you can use this as as starting point for your packaging.

LazPackager would only give a template for a deb package. But as the focus for packaging is an automated system (make, etc.) it would be of not much use once the build scripts are written.

**Comment by markmal** [comment]
Hi Sönke,
How to merge Debian project with Freeship?

**Comment by koendv** [comment]
Debian New Maintainers' Guide:

https://www.debian.org/doc/manuals/maint-guide/

**Comment by markmal** [comment]
I took Sönke's deb template as a base (without real GIT merging, just copied dir from it) and I am working on .deb building. It works. 
Complexity is with adding FreeShip to menu and icons for FreeShip files.
Menu looks like is working.
However there is issue is with icons for .ftm .fbm files, that show up in some linux themes, and do not in other themes.

PS/ Yes, .deb files are convenient way of distribution. On the other side, convenience of scripts is that user can install FreeShip locally, just into the user's home, which is safer. And, of course, it works in any distro.

**Comment by markmal** [comment]
deb is here https://github.com/markmal/freeship-plus-in-lazarus/releases/tag/v3.5.5.7

**Comment by markmal** [comment]
Deb file is available now. I am closing this issue.

**Comment by koendv** [comment]
I've installed the Freeship .deb package on a clean install of debian-8.2.0-amd64. Everything works fine.

Thank you and a happy new year!

koen
