### ISSUE TITLE
Shading model too slow

### ISSUE THREAD

**Issue by tvld** [markmal/freeship-plus-in-lazarus#5]
Seems we are not using the correct hardware accelerated libraries?  Shading and rotating a model on Intel i7 /16GB is too slow to use even.... ?

**Comment by markmal** [comment]
No, we draw via standard graphical functions. It is up to FPC runtime or 
X how to use acceleration.

**Comment by tvld** [comment]
Hm. Then why is the rotating so much slower in Freeship than in the other software I use?... I will investigate more...

**Comment by markmal** [comment]
The issue might be because 3D is completely implemented in FreeShip. All 3D stuff, like Z-buffer, and shading is implemented right in the program, using just primitive 2D graphical functions, like Canvas.Line for lines, or by setting color of pixels directly. Nothing fancy like OpenGL is used (yet).
For shading model, basically, every pixel of every surface is calculated by the program to find if it is visible, and if yes, what will be its color. And given your screen has high resolution, there are many pixels to process.
I am thinking to implement all it in OpenGL. In next major version, probably...

**Comment by markmal** [comment]
I've profiled the app. Yes, it shows what I've said - For shading mode every pixel of every surface (triangle) is calculated by the program to find if it is visible, and if yes, what will be its color.
I've started moving to OpenGL direction...

**Comment by markmal** [comment]
Tom,
Is performance still the issue after rendering was switched to direct memory access?

**Comment by tvld** [comment]
Performance is great now Mark, thanks !
