### ISSUE TITLE
Main dimension precision

### ISSUE THREAD

**Issue by pafurijaz** [markmal/freeship-plus-in-lazarus#61]
Hi in the latest version you have suppressed the zero in the input dialog box now is impossible to setup the right value of the boat because the field lacks in precision because the input have only the support for few floating, Already the old FreeShip is not able to support small objects, if you further reduce precision the accuracy will only be useful for making calculations on huge boats.

![Istantanea_2020-04-06_10-24-54](https://user-images.githubusercontent.com/11751383/78538870-fa657c00-77f1-11ea-9ec9-ce703ad19ec4.png)
![Istantanea_2020-04-06_10-22-31](https://user-images.githubusercontent.com/11751383/78538872-fb96a900-77f1-11ea-94d4-96769377e71e.png)
![Istantanea_2020-04-06_10-22-02](https://user-images.githubusercontent.com/11751383/78538874-fc2f3f80-77f1-11ea-91fe-477b48f8508d.png)

**Comment by markmal** [comment]
For real boats precision of 0.1mm is not practical because anyway nobody can build a boat with such a precision. Unless you are making little models (e.g. 3-d printed). 
Also in many places in calculations tolerances are 1e-4. So except having precise outer dimensions you will not benefit from such precision in calculations results.

It is not a problem to make precision back to 4 decimals after the point. I'll do that. Next release.

**Comment by pafurijaz** [comment]
Thanks, for response :), But anyway was impossible the calculation of hydrostatic for a small objects in fact is impossible take a plausible result from small boat, under 1 mt, Freeship merge the vertexes automatically when they are too close , and that make impossible to calculate such thing as for 3D small objects printed or other kind inside the boat.

**Comment by markmal** [comment]
Please open another issues for:
- "impossible the calculation of hydrostatic for a small objects" and provide with example
- "Freeship merge the vertexes automatically when they are too close" - is it about export? Which export? I need an example too.
